"""empty message

Revision ID: e491923fc48a
Revises: 88fe825bb62a
Create Date: 2021-11-05 13:11:13.866964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e491923fc48a'
down_revision = '88fe825bb62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('defense_wins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('offense_wins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('total_battles', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_battles')
    op.drop_column('user', 'offense_wins')
    op.drop_column('user', 'defense_wins')
    # ### end Alembic commands ###
